export const TICKERS = [
  // Top-of-table, high-volume coins (GeckoTerminal)
  "SOLKR",
  "CATWIFMASK",
  "E91",
  "EVOLVE",
  "NORMIE",
  "BOBR",
  "MOONPIG",
  "PACE",
  "TRUMP",
  "KILLBILL",
  "BIANG",
  "MIXIE",
  "CODED",
  "FARTCOIN",
  "CHILLCAT",
  "AOKUMA",
  "PEPEAI",
  "PIGWIF",
  "CRUISE",
  "LABUBU",
  // Mid-cap / trending (CoinGecko & news flow)
  "PNUT",
  "MOO",
  "ANTCOLONY",
  "CHOMIK",
  "HYPE",
  "WOULD",
  "SOURCE",
  "FOUR",
  "ALON",
  "JAILSTOOL",
  "ELON4AFD",
  "AVA",
  "JUSTACHILLGUY",
  "PEANUTSQUIRREL",
  "MOODENG",
  "PEPEMOON",
  "DADDY",
  "BABYTRUMP",
  "MOTHER",
  "JENNER",
  // Celebrity & culture spins
  "DERULO",
  "RACCOON",
  "KEKW",
  "OINK",
  "DUCKY",
  "DEXTER",
  "SKULL",
  "GOOSE",
  "GOOBER",
  "SQUIRREL",
  // Animal-meme wave
  "SNAIL",
  "CHAD",
  "LARRY",
  "CLOWN",
  "SHREKCOIN",
  "DONKEY",
  "APECOINPUMP",
  "SUSHIDOG",
  "TACOCAT",
  "BURGER",
  // Food-meme wave
  "HOTDOGE",
  "ICECREAM",
  "DONUT",
  "COFFEE",
  "TEACOIN",
  "BEERCOIN",
  "WINEC",
  "VODKA",
  "WHISKY",
  "CATTY",
  // Extra menagerie
  "DOGGO",
  "PENGY",
  "RIBBITZ",
  "TUNG",
  "GOLDFISH",
  "TIGER",
  "LION",
  "BEARCOIN",
  "FOX",
  "KOALA",
  "PANDA",
  "DRAGON",
  "UNICORN",
  "SHIBA",
  "BONKCAT",
  // Degens & slogans
  "NUDES",
  "GROK",
  "XAI",
  "AIPEPE",
  "APEAI",
  "BABYPEPE",
  "MEMECOIN",
  "DEGEN",
  "WAGMI",
  "LFG",
  "NGMI",
  "HODL",
  "MOONSHOT",
  "PUMPCOIN",
  "DUMPIT",
  "BULLRUN",
  "BEARTRAP",
];

export const MEME_TOKENS: Record<string, string> = {
  AIPEPE: "AI Pepe",
  ALON: "Alon",
  ANTCOLONY: "Ant Colony",
  AOKUMA: "Aokuma",
  APEAI: "Ape AI",
  APECOINPUMP: "Ape Coin Pump",
  AVA: "Ava",
  BABYPEPE: "Baby Pepe",
  BABYTRUMP: "Baby Trump",
  BEARCOIN: "Bear Coin",
  BEARTRAP: "Bear Trap",
  BEERCOIN: "Beer Coin",
  BIANG: "Biang",
  BOBR: "Bobr",
  BONK: "Bonk",
  BONKCAT: "Bonk Cat",
  BULLRUN: "Bull Run",
  BURGER: "Burger",
  CATWIFMASK: "Cat Wif Mask",
  CATTY: "Catty",
  CHAD: "Chad",
  CHILLCAT: "Chill Cat",
  CHOMIK: "Chomik",
  CLOWN: "Clown",
  CODED: "Coded",
  COFFEE: "Coffee",
  CRUISE: "Cruise",
  DADDY: "Daddy",
  DEFAULT: "Meme Token",
  DEGEN: "Degen",
  DERULO: "Derulo",
  DEXTER: "Dexter",
  DONKEY: "Donkey",
  DONUT: "Donut",
  DRAGON: "Dragon",
  DUCKY: "Ducky",
  DUMPIT: "Dump It",
  E91: "E91",
  ELON4AFD: "Elon for AFD",
  EVOLVE: "Evolve",
  FARTCOIN: "Fart Coin",
  FOUR: "Four",
  FOX: "Fox",
  GOAT: "Goatseus Maximus",
  GOOBER: "Goober",
  GOLDFISH: "Goldfish",
  GOOSE: "Goose",
  GROK: "Grok",
  HODL: "HODL",
  HOTDOGE: "Hot Doge",
  HYPE: "Hype",
  ICECREAM: "Ice Cream",
  JAILSTOOL: "Jail Stool",
  JENNER: "Jenner",
  JUSTACHILLGUY: "Just a Chill Guy",
  KILLBILL: "Kill Bill",
  KEKW: "KEKW",
  KOALA: "Koala",
  LABUBU: "Labubu",
  LARRY: "Larry",
  LFG: "LFG",
  LION: "Lion",
  MAMA: "Mama",
  MEMECOIN: "Meme Coin",
  MIXIE: "Mixie",
  MOODENG: "Moo Deng",
  MOONPIG: "Moon Pig",
  MOONSHOT: "Moonshot",
  MOO: "Moo",
  MOTHER: "Mother",
  NORMIE: "Normie",
  NGMI: "NGMI",
  NUDES: "Nudes",
  OINK: "Oink",
  PANDA: "Panda",
  PACE: "Pace",
  PEANUTSQUIRREL: "Peanut Squirrel",
  PEPEAI: "Pepe AI",
  PEPEMOON: "Pepe Moon",
  PENGY: "Pengy",
  PNUT: "Peanut the Squirrel",
  PIGWIF: "Pig Wif",
  POPCAT: "Popcat",
  PUMPCOIN: "Pump Coin",
  RABBITZ: "Rabbitz",
  RACCOON: "Raccoon",
  RIBBITZ: "Ribbitz",
  SHIBA: "Shiba",
  SHREKCOIN: "Shrek Coin",
  SKULL: "Skull",
  SNAIL: "Snail",
  SOLKR: "Sol Kr",
  SOURCE: "Source",
  SQUIRREL: "Squirrel",
  SUSHIDOG: "Sushi Dog",
  TACOCAT: "Taco Cat",
  TEACOIN: "Tea Coin",
  TIGER: "Tiger",
  TRUMP: "Trump",
  TUNG: "Tung",
  UNICORN: "Unicorn",
  VODKA: "Vodka",
  WAGMI: "WAGMI",
  WIF: "dogwifhat",
  WHISKY: "Whisky",
  WINEC: "Wine Coin",
  WOULD: "Would",
  XAI: "X AI",
  ZILLA: "Zilla",
};
